// <auto-generated />
using System;
using CSLabs.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSLabs.Api.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CSLabs.Api.Models.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("icon_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("RequiredNumOfModules")
                        .HasColumnType("int")
                        .HasColumnName("required_num_of_modules");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.HasKey("Id")
                        .HasName("pk_badges");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_badges_name");

                    b.ToTable("badges", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.ContactEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_contact_emails");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_contact_emails_email");

                    b.ToTable("contact_emails", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.HypervisorModels.Hypervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Host")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("host");

                    b.Property<string>("NoVncUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("no_vnc_url");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_hypervisors");

                    b.HasIndex("Host")
                        .IsUnique()
                        .HasDatabaseName("ix_hypervisors_host");

                    b.HasIndex("NoVncUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_hypervisors_no_vnc_url");

                    b.ToTable("hypervisors", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.HypervisorModels.HypervisorNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("HypervisorId")
                        .HasColumnType("int")
                        .HasColumnName("hypervisor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<bool>("Primary")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("primary");

                    b.HasKey("Id")
                        .HasName("pk_hypervisor_nodes");

                    b.HasIndex("HypervisorId")
                        .HasDatabaseName("ix_hypervisor_nodes_hypervisor_id");

                    b.HasIndex("Name", "HypervisorId")
                        .IsUnique()
                        .HasDatabaseName("ix_hypervisor_nodes_name_hypervisor_id");

                    b.ToTable("hypervisor_nodes", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.HypervisorModels.HypervisorVmTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("HypervisorNodeId")
                        .HasColumnType("int")
                        .HasColumnName("hypervisor_node_id");

                    b.Property<int>("TemplateVmId")
                        .HasColumnType("int")
                        .HasColumnName("template_vm_id");

                    b.Property<int>("VmTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("vm_template_id");

                    b.HasKey("Id")
                        .HasName("pk_hypervisor_vm_templates");

                    b.HasIndex("HypervisorNodeId")
                        .HasDatabaseName("ix_hypervisor_vm_templates_hypervisor_node_id");

                    b.HasIndex("VmTemplateId")
                        .HasDatabaseName("ix_hypervisor_vm_templates_vm_template_id");

                    b.ToTable("hypervisor_vm_templates", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.HypervisorModels.VmTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("IsCoreRouter")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_core_router");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_vm_template");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_vm_template_owner_id");

                    b.ToTable("vm_template", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_maintenances");

                    b.ToTable("maintenances", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.BridgeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("IsCoreBridge")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_core_bridge");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("pk_bridge_templates");

                    b.HasIndex("LabId")
                        .HasDatabaseName("ix_bridge_templates_lab_id");

                    b.HasIndex("LabId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_bridge_templates_lab_id_name");

                    b.HasIndex("LabId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_bridge_templates_lab_id_uuid");

                    b.ToTable("bridge_templates", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int>("EstimatedCpusUsed")
                        .HasColumnType("int")
                        .HasColumnName("estimated_cpus_used");

                    b.Property<int>("EstimatedMemoryUsedMb")
                        .HasColumnType("int")
                        .HasColumnName("estimated_memory_used_mb");

                    b.Property<int>("LabDifficulty")
                        .HasColumnType("int")
                        .HasColumnName("lab_difficulty");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.HasKey("Id")
                        .HasName("pk_labs");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_labs_module_id");

                    b.HasIndex("Name", "ModuleId")
                        .IsUnique()
                        .HasDatabaseName("ix_labs_name_module_id");

                    b.ToTable("labs", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.LabVm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<bool>("IsCoreRouter")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_core_router");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int>("VmTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("vm_template_id");

                    b.HasKey("Id")
                        .HasName("pk_lab_vms");

                    b.HasIndex("LabId")
                        .HasDatabaseName("ix_lab_vms_lab_id");

                    b.HasIndex("VmTemplateId")
                        .HasDatabaseName("ix_lab_vms_vm_template_id");

                    b.HasIndex("Name", "LabId")
                        .IsUnique()
                        .HasDatabaseName("ix_lab_vms_name_lab_id");

                    b.ToTable("lab_vms", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("Disabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<bool>("Published")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("published");

                    b.Property<string>("SpecialCode")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("special_code");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("SingleUser")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.HasKey("Id")
                        .HasName("pk_modules");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_modules_name");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_modules_owner_id");

                    b.HasIndex("SpecialCode")
                        .IsUnique()
                        .HasDatabaseName("ix_modules_special_code");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.ModuleTag", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("ModuleId", "TagId")
                        .HasName("pk_module_tag");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_module_tag_tag_id");

                    b.ToTable("module_tag", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.VmInterfaceTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BridgeTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("bridge_template_id");

                    b.Property<string>("BridgeTemplateUuid")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bridge_template_uuid");

                    b.Property<int>("InterfaceNumber")
                        .HasColumnType("int")
                        .HasColumnName("interface_number");

                    b.Property<int>("LabVmId")
                        .HasColumnType("int")
                        .HasColumnName("lab_vm_id");

                    b.HasKey("Id")
                        .HasName("pk_vm_interface_templates");

                    b.HasIndex("BridgeTemplateId")
                        .HasDatabaseName("ix_vm_interface_templates_bridge_template_id");

                    b.HasIndex("LabVmId")
                        .HasDatabaseName("ix_vm_interface_templates_lab_vm_id");

                    b.HasIndex("InterfaceNumber", "LabVmId")
                        .IsUnique()
                        .HasDatabaseName("ix_vm_interface_templates_interface_number_lab_vm_id");

                    b.ToTable("vm_interface_templates", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.SystemMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_system_messages");

                    b.ToTable("system_messages", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.SystemStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("HypervisorId")
                        .HasColumnType("int")
                        .HasColumnName("hypervisor_id");

                    b.Property<int>("HypervisorNodesUp")
                        .HasColumnType("int")
                        .HasColumnName("hypervisor_nodes_up");

                    b.Property<bool>("Quorum")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("quorum");

                    b.Property<int>("TotalNodes")
                        .HasColumnType("int")
                        .HasColumnName("total_nodes");

                    b.HasKey("Id")
                        .HasName("pk_system_statuses");

                    b.ToTable("system_statuses", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.BridgeInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BridgeTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("bridge_template_id");

                    b.Property<int>("HypervisorInterfaceId")
                        .HasColumnType("int")
                        .HasColumnName("hypervisor_interface_id");

                    b.Property<int>("UserLabId")
                        .HasColumnType("int")
                        .HasColumnName("user_lab_id");

                    b.HasKey("Id")
                        .HasName("pk_bridge_instances");

                    b.HasIndex("BridgeTemplateId")
                        .HasDatabaseName("ix_bridge_instances_bridge_template_id");

                    b.HasIndex("UserLabId")
                        .HasDatabaseName("ix_bridge_instances_user_lab_id");

                    b.HasIndex("UserLabId", "HypervisorInterfaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_bridge_instances_user_lab_id_hypervisor_interface_id");

                    b.ToTable("bridge_instances", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CardCodeHash")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("card_code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(45)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationCode")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("email_verification_code");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("first_name");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("int")
                        .HasColumnName("graduation_year");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("PasswordRecoveryCode")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("password_recovery_code");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<bool>("SubscribedNewsletter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("subscribed_newsletter");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("termination_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CardCodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_users_card_code_hash");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("PasswordRecoveryCode")
                        .IsUnique()
                        .HasDatabaseName("ix_users_password_recovery_code");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.UserLab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date_time");

                    b.Property<int?>("HypervisorNodeId")
                        .HasColumnType("int")
                        .HasColumnName("hypervisor_node_id");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_used");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int>("UserModuleId")
                        .HasColumnType("int")
                        .HasColumnName("user_module_id");

                    b.HasKey("Id")
                        .HasName("pk_user_labs");

                    b.HasIndex("EndDateTime")
                        .HasDatabaseName("ix_user_labs_end_date_time");

                    b.HasIndex("HypervisorNodeId")
                        .HasDatabaseName("ix_user_labs_hypervisor_node_id");

                    b.HasIndex("LabId")
                        .HasDatabaseName("ix_user_labs_lab_id");

                    b.HasIndex("UserModuleId")
                        .HasDatabaseName("ix_user_labs_user_module_id");

                    b.HasIndex("UserModuleId", "LabId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_labs_user_module_id_lab_id");

                    b.ToTable("user_labs", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.UserLabVm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int>("HypervisorVmTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("hypervisor_vm_template_id");

                    b.Property<bool>("IsCoreRouter")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_core_router");

                    b.Property<int>("LabVmId")
                        .HasColumnType("int")
                        .HasColumnName("lab_vm_id");

                    b.Property<int>("ProxmoxVmId")
                        .HasColumnType("int")
                        .HasColumnName("proxmox_vm_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int>("UserLabId")
                        .HasColumnType("int")
                        .HasColumnName("user_lab_id");

                    b.HasKey("Id")
                        .HasName("pk_user_lab_vms");

                    b.HasIndex("HypervisorVmTemplateId")
                        .HasDatabaseName("ix_user_lab_vms_hypervisor_vm_template_id");

                    b.HasIndex("LabVmId")
                        .HasDatabaseName("ix_user_lab_vms_lab_vm_id");

                    b.HasIndex("UserLabId")
                        .HasDatabaseName("ix_user_lab_vms_user_lab_id");

                    b.HasIndex("UserLabId", "LabVmId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_lab_vms_user_lab_id_lab_vm_id");

                    b.ToTable("user_lab_vms", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.UserModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<DateTime>("TerminationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("termination_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.HasKey("Id")
                        .HasName("pk_user_modules");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_user_modules_module_id");

                    b.ToTable("user_modules", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.UserUserModule", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("UserModuleId")
                        .HasColumnType("int")
                        .HasColumnName("user_module_id");

                    b.HasKey("UserId", "UserModuleId")
                        .HasName("pk_user_user_module");

                    b.HasIndex("UserModuleId")
                        .HasDatabaseName("ix_user_user_module_user_module_id");

                    b.ToTable("user_user_module", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.VmInterfaceInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BridgeInstanceId")
                        .HasColumnType("int")
                        .HasColumnName("bridge_instance_id");

                    b.Property<int>("UserLabVmId")
                        .HasColumnType("int")
                        .HasColumnName("user_lab_vm_id");

                    b.Property<int>("VmInterfaceTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("vm_interface_template_id");

                    b.HasKey("Id")
                        .HasName("pk_vm_interface_instances");

                    b.HasIndex("BridgeInstanceId")
                        .HasDatabaseName("ix_vm_interface_instances_bridge_instance_id");

                    b.HasIndex("UserLabVmId")
                        .HasDatabaseName("ix_vm_interface_instances_user_lab_vm_id");

                    b.HasIndex("VmInterfaceTemplateId")
                        .HasDatabaseName("ix_vm_interface_instances_vm_interface_template_id");

                    b.ToTable("vm_interface_instances", (string)null);
                });

            modelBuilder.Entity("CSLabs.Api.Models.HypervisorModels.HypervisorNode", b =>
                {
                    b.HasOne("CSLabs.Api.Models.HypervisorModels.Hypervisor", "Hypervisor")
                        .WithMany("HypervisorNodes")
                        .HasForeignKey("HypervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hypervisor_nodes_hypervisors_hypervisor_id");

                    b.Navigation("Hypervisor");
                });

            modelBuilder.Entity("CSLabs.Api.Models.HypervisorModels.HypervisorVmTemplate", b =>
                {
                    b.HasOne("CSLabs.Api.Models.HypervisorModels.HypervisorNode", "HypervisorNode")
                        .WithMany()
                        .HasForeignKey("HypervisorNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hypervisor_vm_templates_hypervisor_nodes_hypervisor_node_id");

                    b.HasOne("CSLabs.Api.Models.HypervisorModels.VmTemplate", "VmTemplate")
                        .WithMany("HypervisorVmTemplates")
                        .HasForeignKey("VmTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hypervisor_vm_templates_vm_template_vm_template_id");

                    b.Navigation("HypervisorNode");

                    b.Navigation("VmTemplate");
                });

            modelBuilder.Entity("CSLabs.Api.Models.HypervisorModels.VmTemplate", b =>
                {
                    b.HasOne("CSLabs.Api.Models.UserModels.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_vm_template_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.BridgeTemplate", b =>
                {
                    b.HasOne("CSLabs.Api.Models.ModuleModels.Lab", "Lab")
                        .WithMany("BridgeTemplates")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bridge_templates_labs_lab_id");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.Lab", b =>
                {
                    b.HasOne("CSLabs.Api.Models.ModuleModels.Module", "Module")
                        .WithMany("Labs")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_labs_modules_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.LabVm", b =>
                {
                    b.HasOne("CSLabs.Api.Models.ModuleModels.Lab", "Lab")
                        .WithMany("LabVms")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lab_vms_labs_lab_id");

                    b.HasOne("CSLabs.Api.Models.HypervisorModels.VmTemplate", "VmTemplate")
                        .WithMany()
                        .HasForeignKey("VmTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lab_vms_vm_template_vm_template_id");

                    b.Navigation("Lab");

                    b.Navigation("VmTemplate");
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.Module", b =>
                {
                    b.HasOne("CSLabs.Api.Models.UserModels.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("fk_modules_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.ModuleTag", b =>
                {
                    b.HasOne("CSLabs.Api.Models.ModuleModels.Module", "Module")
                        .WithMany("ModuleTags")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_module_tag_modules_module_id");

                    b.HasOne("CSLabs.Api.Models.ModuleModels.Tag", "Tag")
                        .WithMany("ModuleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_module_tag_tags_tag_id");

                    b.Navigation("Module");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.VmInterfaceTemplate", b =>
                {
                    b.HasOne("CSLabs.Api.Models.ModuleModels.BridgeTemplate", "BridgeTemplate")
                        .WithMany()
                        .HasForeignKey("BridgeTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vm_interface_templates_bridge_templates_bridge_template_id");

                    b.HasOne("CSLabs.Api.Models.ModuleModels.LabVm", "LabVm")
                        .WithMany("TemplateInterfaces")
                        .HasForeignKey("LabVmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vm_interface_templates_lab_vms_lab_vm_id");

                    b.Navigation("BridgeTemplate");

                    b.Navigation("LabVm");
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.BridgeInstance", b =>
                {
                    b.HasOne("CSLabs.Api.Models.ModuleModels.BridgeTemplate", "BridgeTemplate")
                        .WithMany()
                        .HasForeignKey("BridgeTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bridge_instances_bridge_templates_bridge_template_id");

                    b.HasOne("CSLabs.Api.Models.UserModels.UserLab", "UserLab")
                        .WithMany("BridgeInstances")
                        .HasForeignKey("UserLabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bridge_instances_user_labs_user_lab_id");

                    b.Navigation("BridgeTemplate");

                    b.Navigation("UserLab");
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.UserLab", b =>
                {
                    b.HasOne("CSLabs.Api.Models.HypervisorModels.HypervisorNode", "HypervisorNode")
                        .WithMany("UserLabs")
                        .HasForeignKey("HypervisorNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_labs_hypervisor_nodes_hypervisor_node_id");

                    b.HasOne("CSLabs.Api.Models.ModuleModels.Lab", "Lab")
                        .WithMany("UserLabs")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_labs_labs_lab_id");

                    b.HasOne("CSLabs.Api.Models.UserModels.UserModule", "UserModule")
                        .WithMany("UserLabs")
                        .HasForeignKey("UserModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_labs_user_modules_user_module_id");

                    b.Navigation("HypervisorNode");

                    b.Navigation("Lab");

                    b.Navigation("UserModule");
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.UserLabVm", b =>
                {
                    b.HasOne("CSLabs.Api.Models.HypervisorModels.HypervisorVmTemplate", "HypervisorVmTemplate")
                        .WithMany()
                        .HasForeignKey("HypervisorVmTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_lab_vms_hypervisor_vm_templates_hypervisor_vm_template_");

                    b.HasOne("CSLabs.Api.Models.ModuleModels.LabVm", "LabVm")
                        .WithMany()
                        .HasForeignKey("LabVmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_lab_vms_lab_vms_lab_vm_id");

                    b.HasOne("CSLabs.Api.Models.UserModels.UserLab", "UserLab")
                        .WithMany("UserLabVms")
                        .HasForeignKey("UserLabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_lab_vms_user_labs_user_lab_id");

                    b.Navigation("HypervisorVmTemplate");

                    b.Navigation("LabVm");

                    b.Navigation("UserLab");
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.UserModule", b =>
                {
                    b.HasOne("CSLabs.Api.Models.ModuleModels.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_modules_modules_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.UserUserModule", b =>
                {
                    b.HasOne("CSLabs.Api.Models.UserModels.User", "User")
                        .WithMany("UserUserModules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_user_module_users_user_id");

                    b.HasOne("CSLabs.Api.Models.UserModels.UserModule", "UserModule")
                        .WithMany("UserUserModules")
                        .HasForeignKey("UserModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_user_module_user_modules_user_module_id");

                    b.Navigation("User");

                    b.Navigation("UserModule");
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.VmInterfaceInstance", b =>
                {
                    b.HasOne("CSLabs.Api.Models.UserModels.BridgeInstance", "BridgeInstance")
                        .WithMany("InterfaceInstances")
                        .HasForeignKey("BridgeInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vm_interface_instances_bridge_instances_bridge_instance_id");

                    b.HasOne("CSLabs.Api.Models.UserModels.UserLabVm", "UserLabVm")
                        .WithMany("InterfaceInstances")
                        .HasForeignKey("UserLabVmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vm_interface_instances_user_lab_vms_user_lab_vm_id");

                    b.HasOne("CSLabs.Api.Models.ModuleModels.VmInterfaceTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("VmInterfaceTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vm_interface_instances_vm_interface_templates_vm_interface_t");

                    b.Navigation("BridgeInstance");

                    b.Navigation("Template");

                    b.Navigation("UserLabVm");
                });

            modelBuilder.Entity("CSLabs.Api.Models.HypervisorModels.Hypervisor", b =>
                {
                    b.Navigation("HypervisorNodes");
                });

            modelBuilder.Entity("CSLabs.Api.Models.HypervisorModels.HypervisorNode", b =>
                {
                    b.Navigation("UserLabs");
                });

            modelBuilder.Entity("CSLabs.Api.Models.HypervisorModels.VmTemplate", b =>
                {
                    b.Navigation("HypervisorVmTemplates");
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.Lab", b =>
                {
                    b.Navigation("BridgeTemplates");

                    b.Navigation("LabVms");

                    b.Navigation("UserLabs");
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.LabVm", b =>
                {
                    b.Navigation("TemplateInterfaces");
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.Module", b =>
                {
                    b.Navigation("Labs");

                    b.Navigation("ModuleTags");
                });

            modelBuilder.Entity("CSLabs.Api.Models.ModuleModels.Tag", b =>
                {
                    b.Navigation("ModuleTags");
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.BridgeInstance", b =>
                {
                    b.Navigation("InterfaceInstances");
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.User", b =>
                {
                    b.Navigation("UserUserModules");
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.UserLab", b =>
                {
                    b.Navigation("BridgeInstances");

                    b.Navigation("UserLabVms");
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.UserLabVm", b =>
                {
                    b.Navigation("InterfaceInstances");
                });

            modelBuilder.Entity("CSLabs.Api.Models.UserModels.UserModule", b =>
                {
                    b.Navigation("UserLabs");

                    b.Navigation("UserUserModules");
                });
#pragma warning restore 612, 618
        }
    }
}
