name: Build
on:
  push:
    branches:
      - master
      - dev
      - jc/sonarcloud-dotnet-6
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: SonarScanner for .NET 6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: highbyte/sonarscan-dotnet@v2.1.2
        with:
          sonarProjectKey: ius-csg_cslabs-backend
          sonarProjectName: cslabs-backend
          sonarOrganization: ius-csg